version: '3.8'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    platform: linux/arm64
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ollama

networks:
  ollama:
    driver: bridge
    name: ollama-network
